sap.ui.define([], function() {
	"use strict";

	return {
		REPORT_TYPE_WORK: "WORK",
		REPORT_TYPE_SCHOOL: "SCHOOL",
		REPORT_TYPE_COMBINED: "COMBINED",
		REPORT_TYPE_DAILY: "DAILY",

		REPORT_STATUS_NEW: "NEW",
		REPORT_STATUS_TRAINER: "TRAINER",
		REPORT_STATUS_HEAD: "HEAD",
		REPORT_STATUS_APPROVED: "APPROVED",
		REPORT_STATUS_REJECTED: "REJECTED",

		NO_DEPARTMENT: "NONE"
	};

});